config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('myportfolio.urls')),
] 

myportfolio/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'myportfolio'

urlpatterns = [path('', views.homepage, name='homepage'),
               path('home/', views.homepage, name='home'),

               path('login/', views.login_view, name='login'),
               path('logout/', views.logout_view, name='logout'),

#               path('aboutme/', views.edit_degree, name='aboutme'),
               path('aboutme/degree/', views.degree, name='degree'),
               path('aboutme/degree/create/',views.create_degree, name='create_degree'),
               path('aboutme/degree/edit/<int:degree_id>',views.edit_degree, name='adedit'),
               path('aboutme/degree/delete/<int:degree_id>',views.delete_degree, name='delete_degree'),

               path('aboutme/education/', views.education, name='education'),
               path('aboutme/education/create/',views.create_education, name='create_education'),
               path('aboutme/education/edit/<int:institution_id>',views.edit_education, name='aeedit'),
               path('aboutme/education/delete/<int:institution_id>',views.delete_education, name='delete_education'),

               path('aboutme/skills/', views.skills, name='skills'),
               path('aboutme/interests/', views.interests, name='interests'),
               path('aboutme/profexperience/',views.profexperience, name='profexperience'),

               path('projects/collegeproj', views.collegeproj, name='collegeproj'),
               path('projects/myprojects', views.myprojects, name='myprojects'),
               path('projects/finalprojects',views.finalprojects, name='finalprojects'),

               path('pw/technologies/tfrontend', views.tfrontend, name='tfrontend'),
               path('pw/technologies/tbackend', views.tbackend, name='tbackend'),
               path('pw/tlabs', views.tlabs, name='tlabs'),
               path('pw/tnews', views.tnews, name='tnews'),

               path('testimonials/', views.testimonials, name='testimonials'),
               path('cta/', views.cta, name='cta'),

               # Blog section
               path('blog/', views.blog, name='blog'),
               path('blog/newpost/', views.new_post, name='new_post'),
               path('blog/edit/<int:post_id>', views.post_edit, name='post_edit'),
               path('blog/delete/<int:post_id>', views.post_delete, name='post_delete'),               

               # About this site
               path('aboutthissite/atechnologies', views.atechnologies, name='atechnologies'),
               path('aboutthissite/astandards', views.astandards, name='astandards'),
               path('sitemap', views.sitemap, name='sitemap'),

               ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myportfolio/models.py
from django.db import models


education_stages = (
    ("degree", "Degree"),
    ("middle-school", "Middle-School"),
    ("certification", "Certification"),
)

degree_semester = (
    (1, 1),
    (2, 2),    
)

degree_year = (
    (1, 1),
    (2, 2),    
)



class Institution(models.Model):
    
    name = models.CharField(max_length=50)
    location = models.CharField(max_length=80)
    webpage = models.CharField(blank=True,max_length=100)    
    logo = models.ImageField(
        upload_to='media', blank=True)

    def __str__(self):
        return self.name


class Degree(models.Model):
    
    institution = models.ForeignKey(
        Institution, on_delete=models.CASCADE, related_name='degrees')
    name = models.CharField(max_length=80)
    abbrev = models.CharField(blank=True,max_length=10)
    start_date = models.DateField()
    end_date = models.DateField()

    def __str__(self):
        return self.name
    
class Teacher(models.Model):
    
    name = models.CharField(max_length=100)
    profile_url = models.URLField(blank=True,max_length=30)
    smprofile_url = models.URLField(blank=True,max_length=30)
    def __str__(self):
        return self.name

class Class(models.Model):
    
    degree = models.ManyToManyField(Degree, related_name='classes')
    name = models.CharField(max_length=100)
    teachers = models.ManyToManyField(Teacher, related_name='teaches')
    semester = models.IntegerField(choices=degree_semester,default=1)
    year = models.IntegerField(choices=degree_year,default=1)
    def __str__(self):
        return self.name

class Student(models.Model):
    
    name = models.CharField(max_length=100)
    degrees = models.ManyToManyField(Degree, related_name='students')
    def __str__(self):
        return self.name

class Post(models.Model):
    
    author = models.CharField(max_length=100)
    title = models.CharField(max_length=200)
    description = models.TextField()
    image = models.ImageField(
        upload_to='media/myportfolio/img/', blank=True)
    url = models.URLField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

myportfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Degree

from .models import Institution, Degree, Class, Teacher, Student, Post

class InstitutionForm(ModelForm):
    class Meta:
        model = Institution
        fields = '__all__'

class DegreeForm(ModelForm):
    class Meta:
        model = Degree
        fields = '__all__'

class ClassForm(ModelForm):
    class Meta:
        model = Class
        fields = '__all__'

class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'

class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

myportfolio/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .models import Institution, Degree, Class, Teacher, Student, Post
from .forms import InstitutionForm, DegreeForm, ClassForm, TeacherForm, StudentForm, PostForm

def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('myportfolio:home')
        else:
            error = 'Invalid login credentials'
            return render(request, 'myportfolio/login.html', {'error': error})
    else:
        return render(request, 'myportfolio/login.html')


def logout_view(request):
    logout(request)
    return redirect('myportfolio:home')


def homepage(request):

    return render(request, 'myportfolio/home.html')


def aboutme(request):

    return render(request, 'myportfolio/aboutme.html')


def education(request):
    institution = Institution.objects.all()
    return render(request, 'myportfolio/education.html', {'institution': institution})


def degree(request):
    degrees = Degree.objects.all()
    return render(request, 'myportfolio/degree.html', {'degrees': degrees})


""" @login_required """


def create_degree(request):
    if request.method == 'POST':
        form = DegreeForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myportfolio:education')
    else:
        form = DegreeForm()
    return render(request, 'myportfolio/create_degree.html', {'form': form})


def edit_degree(request, degree_id):
    try:
        degree = Degree.objects.get(id=degree_id)
    except Degree.DoesNotExist:
        return redirect('myportfolio:education')

    if request.method == 'POST':
        form = DegreeForm(request.POST, instance=degree)
        if form.is_valid():
            form.save()
            return redirect('myportfolio:education')
    else:
        form = DegreeForm(instance=degree)

    return render(request, 'myportfolio/edit_degree.html', {'form': form, 'degree': degree})


def delete_degree(request, degree_id):
    try:
        degree = Degree.objects.get(id=degree_id)
    except Degree.DoesNotExist:
        return redirect('myportfolio:education')

    if request.method == 'POST':
        degree.delete()
        return redirect('myportfolio:education')

    return render(request, 'myportfolio/delete_degree.html', {'degree': degree})

# EDUCATION PART
def create_education(request):
    if request.method == 'POST':
        form = InstitutionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myportfolio:education')
    else:
        form = InstitutionForm()
    return render(request, 'myportfolio/create_education.html', {'form': form})


def edit_education(request, institution_id):
    try:
        institution = Institution.objects.get(id=institution_id)
    except Institution.DoesNotExist:
        return redirect('myportfolio:education')

    if request.method == 'POST':
        form = InstitutionForm(request.POST, instance=institution)
        if form.is_valid():
            form.save()
            return redirect('myportfolio:education')
    else:
        form = InstitutionForm(instance=institution)

    return render(request, 'myportfolio/edit_education.html', {'form': form, 'institution': institution})


def delete_education(request, institution_id):
    try:
        institution = Institution.objects.get(id=institution_id)
    except Institution.DoesNotExist:
        return redirect('myportfolio:education')

    if request.method == 'POST':
        institution.delete()
        return redirect('myportfolio:education')

    return render(request, 'myportfolio/delete_education.html', {'institution': institution})


def skills(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/skills.html', {'Institution': schools})


def interests(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/interests.html', {'Institution': schools})


def profexperience(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/profexperience.html', {'Institution': schools})


def collegeproj(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/collegeproj.html', {'Institution': schools})


def myprojects(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/myprojects.html', {'Institution': schools})


def finalprojects(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/finalprojects.html', {'Institution': schools})


def tfrontend(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/tfrontend.html', {'Institution': schools})


def tbackend(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/tbackend.html', {'Institution': schools})


def tlabs(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/tlabs.html', {'Institution': schools})


def tnews(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/tnews.html', {'Institution': schools})


def testimonials(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/testimonials.html', {'Institution': schools})


def cta(request):

    return render(request, 'myportfolio/cta.html')


def blog(request):
    posts = sorted(Post.objects.all(),
                   key=lambda objecto: objecto.created_at, reverse=True)
    return render(request, 'myportfolio/blog.html', {'posts': posts})



def atechnologies(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/atechnologies.html', {'schools': schools})


def astandards(request):
    schools = Institution.objects.all()
    return render(request, 'myportfolio/astandards.html', {'schools': schools})

def new_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myportfolio:blog')
    else:
        form = PostForm()
    return render(request, 'myportfolio/post_create.html', {'form': form})



def post_edit(request, post_id):
    try:
        post = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        return redirect('myportfolio:blog')

    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('myportfolio:blog')
    else:
        form = PostForm(instance=post)

    return render(request, 'myportfolio/post_edit.html', {'form': form, 'institution': post})








def post_delete(request, post_id):
    try:
        post = Post.objects.get(id=post_id)
    except Post.DoesNotExist:
        return redirect('myportfolio:blog')

    if request.method == 'POST':
        post.delete()
        return redirect('myportfolio:blog')

    return render(request, 'myportfolio/post_delete.html', {'post': post})


def sitemap(request):

    return render(request, 'myportfolio/sitemap.html')

myportfolio/templates/myportfolio/atechnologies.html
{% extends 'myportfolio/base.html' %}

{% load static %}

{% block hero %}


<div>
    <hr>
    <h3 id="active">Education</h3>
</div>

{% endblock %}

{% block title %}

<h3 id="education">My path in education</h3>


{% endblock %}


{% block main %}
<div>
    <h1>atechnologies</h1>


    {% for school in schools %}

    <img src="{{ school.logo.url }}" maxweight="50px" max height="50px" alt="{{ school.name }} Logo">
    <br>
    <p>{{ school.name }}</p>
    <p>{{ school.location }}</p>
    <p>{{ school.start_date }}</p>
    <p>{{ school.end_date }}</p>

    {% endfor %}
</div>

{% endblock %}

myportfolio/templates/myportfolio/base.html
<DOCTYPE html>

    <html>

    <head>

        {% load static %}

        <!-- <link rel="shortcut icon" type="image/png" href="{% static 'myportfolio/img/favicon.png' %}"> -->

        <link id="mystylesheet" rel="stylesheet" href="{% static 'myportfolio/css/base.css' %}">

        <!--  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
        -->
        <!-- For the button -->
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.7/css/all.css">
        <link rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="Rui Pedro Correia - IT DevOps Engineer">
        <meta name="author" content="Rui Pedro Correia">
        <meta name="keywords" content="Porfolio">

        <script src="{% static 'myportfolio/js/scripts.js' %}"></script>
        <title>Rui Pedro Correia | Portfolio</title>

    </head>

    <body>
        <header class="header menu">
            <div class="topmenu">
                <ul>
                    <li><a href="{% url 'myportfolio:home' %}">Home</a></li>

                    <div class="dropdown">
                        <button class="dropbtn">AboutMe</button>
                        <div class="dropdown-content">
                            <a href="{% url 'myportfolio:degree' %}">Degree</a>
                            <a href="{% url 'myportfolio:education' %}">Education</a>
                            <a href="{% url 'myportfolio:skills' %}">Skills</a>
                            <a href="{% url 'myportfolio:interests' %}">Interests and Hobbies</a>
                            <a href="{% url 'myportfolio:profexperience' %}">Professional Experience</a>
                        </div>
                    </div>

                    <div class="dropdown">
                        <button class="dropbtn">Projects</button>
                        <div class="dropdown-content">
                            <a href="{% url 'myportfolio:collegeproj' %}">College Projects</a>
                            <a href="{% url 'myportfolio:myprojects' %}">My Projects</a>
                            <a href="{% url 'myportfolio:finalprojects' %}">TFC Projects</a>
                        </div>
                    </div>

                    <div class="dropdown">
                        <button class="dropbtn">WebProgramming</button>
                        <div class="dropdown-content">
                            <a href="{% url 'myportfolio:tlabs' %}">Labs</a>
                            <a href="{% url 'myportfolio:tnews' %}">News</a>
                            <div class="subdropdown">
                                <button class="dropbtn">Technologies</button>
                                <div class="dropdown-subcontent">
                                    <a href="{% url 'myportfolio:tfrontend' %}">Front-End</a>
                                    <a href="{% url 'myportfolio:tbackend' %}">Back-end</a>

                                </div>
                            </div>
                        </div>
                    </div>
                    <li><a href="{% url 'myportfolio:testimonials' %}">Testimonials</a></li>
                    <li><a href="{% url 'myportfolio:blog' %}" target="_blank">Blog</a></li>
                    <div class="dropdown">
                        <button class="dropbtn">About</button>
                        <div class="dropdown-content">
                            <a href="{% url 'myportfolio:atechnologies' %}">Technologies</a>
                            <a href="{% url 'myportfolio:astandards' %}">Standards</a>
                        </div>
                    </div>
                    <li><a href="{% url 'myportfolio:sitemap' %}">Site Map</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'myportfolio:logout' %}" onclick="logoutAlert()">Logout</a></li>

                    {% else %}
                    <li><a href="{% url 'myportfolio:login' %}">Login</a></li>
                    {% endif %}

                    <!-- <li><a href="{% url 'myportfolio:new_post' %}">Create Post</a></li> -->


                    <li class="weather-info" id="weather-info">

                    <li class="dark-mode-toggle">
                        <!-- Dark Theme Toggle  -->
                        <button id="dark-mode-toggle" class='darkmode'><i class="fas fa-moon"
                                onclick="toggleTheme('dark');"></i></button>
                    </li>
                </ul>


            </div>
        </header>



        <div class="grid-container">
            <div class="grid-header"></div>

            <div class="grid-hero">

                <figure>
                    <div class="circle"></div>
                </figure>
                <div>
                    <h2 id="active">Hey there, I'm Rui!</h2>
                </div>




                {% block hero %}

                {% endblock %}

                <!--  work with me
                <li><a href="#workwithme">Contact</a></li> -->

            </div>

            <!-- <div class="grid sidebar">Sidebar</div> -->

            <div class="grid-content">
                <main class="container-main">
                    <!-- background video display -->
                    <video autoplay muted loop id="mybkVideo">
                        <source src="{% static 'myportfolio/video/datacenter.mp4' %}" type="video/mp4">
                    </video>

                    {% block title %}

                    {% endblock %}

                    {% block main %}

                    {% endblock %}

                </main>
            </div>


            <div class="grid extra">
                <section id="workwithme">
                    <div>
                        <h2>Work with me!</h2>

                        <p>If you are interested in working with me, please fill out<br> the form below and I will get
                            back to
                            you as soon as possible.</p>
                        <form>
                            <label for="name">Name:</label>
                            <input type="text" id="name" name="name"><br><br>
                            <label for="email">Email:</label>
                            <input type="email" id="email" name="email"><br><br>
                            <label for="message">Message:</label><br>
                            <textarea id="message" name="message"></textarea><br><br>
                            <input type="submit" value="Submit">
                        </form>
                    </div>
                </section>
                <div class="social-icons">
                    <a href="https://www.facebook.com" target="_blank" class="fa fa-facebook"></a>
                    <a href="https://www.twitter.com" target="_blank" class="fa fa-twitter"></a>
                    <a href="https://www.linkedin.com" target="_blank" class="fa fa-linkedin"></a>
                    <a href="https://www.skype.com" target="_blank" class="fa fa-skype"></a>
                </div>
            </div>

            <div class="grid related-images">
                <img src="/static/myportfolio/img/siro-logo.png" maxweight="50px" max height="50px"
                    alt="{{ school.name }} NoLogo">
                <img src="/static/myportfolio/img/celfocus-white.png" maxweight="50px" max height="50px"
                    alt="{{ school.name }} NoLogo">
                <img src="/static/myportfolio/img/novabase.png" maxweight="50px" max height="50px"
                    alt="{{ school.name }} NoLogo">
                <img src="/static/myportfolio/img/teleperformance.png" maxweight="50px" max height="50px"
                    alt="{{ school.name }} NoLogo">
                <img src="/static/myportfolio/img/intrum.png" maxweight="50px" max height="50px"
                    alt="{{ school.name }} NoLogo">
            </div>

            <div class="grid related-posts">

            </div>

            <div class="grid footer">
                <div>
                    <a href="{% url 'myportfolio:sitemap' %}">Site Map |</a>
                    <p>Copyright © 2023 Rui Pedro Correia |</p>
                    <a rel="noopener" href="#workwithme">WorkWithMe! |</a>
                    <p>ULHT |</p>
                    <p>Copyright © 2023 Rui Pedro Correia |</p>
                </div>
            </div>
        </div>
    </body>

    </html>

myportfolio/templates/myportfolio/collegeproj.html
{% extends 'myportfolio/base.html' %}

{% load static %}

{% block hero %}


<div>
    <hr>
    <h3 id="active">Education</h3>
</div>

{% endblock %}

{% block title %}

<h3 id="education">My path in education</h3>


{% endblock %}


{% block main %}
<div>
    <h1>collegeproj</h1>


    {% for school in schools %}

    <img src="{{ school.logo.url }}" maxweight="50px" max height="50px" alt="{{ school.name }} Logo">
    <br>
    <p>{{ school.name }}</p>
    <p>{{ school.location }}</p>
    <p>{{ school.start_date }}</p>
    <p>{{ school.end_date }}</p>

    {% endfor %}
</div>

{% endblock %}

myportfolio/templates/myportfolio/education.html
{% extends 'myportfolio/base.html' %}

{% load static %}

{% block hero %}

<div>
    <hr>
    <h3 id="active">Education</h3>
</div>

{% endblock %}

{% block title %}

<h3 id="degree">See my path bellow</h3>


{% endblock %}


{% block main %}

<h1>Education</h1>
{% if user.is_authenticated %}
<a href="{% url 'myportfolio:create_education' %}">Create Education</a>
{% endif %}

<div class="container-box">
    <div class="row">

        {% for institution in institution %}
        <div class="column">
            <div class="content-education">

                {% if institution.logo %}
                <img src="{{ institution.logo.url }}" maxweight="50px" max height="50px" alt="{{ school.name }} Logo">
                {% else %}

                <img src="/static/myportfolio/img/default.png" maxweight="50px" max height="50px"
                    alt="{{ school.name }} NoLogo">
                {% endif %}
                <h2>School name:</h2>
                {{ institution.name }}

                <p>Location:</p>
                {{ institution.location }}

                <p>Webpage:</p>
                {% if institution.webpage %}
                {{ institution.webpage }}
                {% else %}
                <p>None</p>
                {% endif %}

                {% if user.is_authenticated %}

                <a href="{% url 'myportfolio:aeedit' institution.id %}">Edit School</a>
                <a href="{% url 'myportfolio:delete_education' institution.id %}">Delete School</a>

                {% endif %}



            </div>
        </div>
        {% endfor %}
    </div>
</div>


{% endblock %}

myportfolio/templates/myportfolio/interests.html
{% extends 'myportfolio/base.html' %}

{% load static %}

{% block hero %}


<div>
    <hr>
    <h3 id="active">Education</h3>
</div>

{% endblock %}

{% block title %}

<h3 id="education">My path in education</h3>


{% endblock %}


{% block main %}
<div>
    <h1>INTERESTS</h1>


    {% for school in schools %}

    <img src="{{ school.logo.url }}" maxweight="50px" max height="50px" alt="{{ school.name }} Logo">
    <br>
    <p>{{ school.name }}</p>
    <p>{{ school.location }}</p>
    <p>{{ school.start_date }}</p>
    <p>{{ school.end_date }}</p>

    {% endfor %}
</div>

{% endblock %}

myportfolio/templates/myportfolio/nova_pagina.html
{% extends 'myportfolio/base.html' %}

{% block main %}

<form method="POST" action="">
    <!-- Avoid attacks by validating the token -->
    {% csrf_token %}

    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

{% endblock %}

myportfolio/templates/myportfolio/post_delete.html
<!DOCTYPE html>

{% extends 'myportfolio/base.html' %}

{% block main %}

<h1>Delete Post</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <label for="title">Title:</label>
  <input type="text" name="title" value="{{ post.title }}" required>
  <br>
  <label for="description">Description:</label>
  <textarea name="description" required>{{ post.description }}</textarea>
  <br>
  <label for="image">Image:</label>
  <input type="file" name="image">
  <br>
  <label for="url">URL:</label>
  <input type="url" name="url" value="{{ post.url }}">
  <br>
  <input type="submit" value="Delete">
</form>
{% endblock %}

myportfolio/templates/myportfolio/post_detail.html
{% extends 'myportfolio/base.html' %}

{% block main %}

<h1>Blog Posts</h1>
<ul>
  {% for post.pk = posts.pk %}
  <li>
    <p>Title: {{ post.title }}</p>
    <p>Author: {{ post.author }}</p>
    <p>Date: {{ post.created_at }}</p>
    <p>Image {{ post.image }}</p>
    <img src="{% static '{{post.image}}'%}" alt="">
    <p>Description: {{ post.description }}</p>
  </li>
  {% empty %}
  <p>No posts yet.</p>
  {% endfor %}
</ul>
{% endblock %}

myportfolio/templates/myportfolio/profexperience.html
{% extends 'myportfolio/base.html' %}

{% load static %}

{% block hero %}


<div>
    <hr>
    <h3 id="active">Education</h3>
</div>

{% endblock %}

{% block title %}

<h3 id="education">My path in education</h3>


{% endblock %}


{% block main %}
<div>
    <h1>PROFESSIONAL EXPERIENCE</h1>


    {% for school in schools %}

    <img src="{{ school.logo.url }}" maxweight="50px" max height="50px" alt="{{ school.name }} Logo">
    <br>
    <p>{{ school.name }}</p>
    <p>{{ school.location }}</p>
    <p>{{ school.start_date }}</p>
    <p>{{ school.end_date }}</p>

    {% endfor %}
</div>

{% endblock %}

myportfolio/templates/myportfolio/projects.html
{% extends 'myportfolio/base.html' %}

{% load static %}


{% block title %}
<div>Projects</div>
{% endblock %}


{% block main %}

<div>Vodafone Ireland - Fiber</div>

{% endblock %}

myportfolio/templates/myportfolio/tbackend.html
{% extends 'myportfolio/base.html' %}

{% load static %}

{% block hero %}


<div>
    <hr>
    <h3 id="active">Education</h3>
</div>

{% endblock %}

{% block title %}

<h3 id="education">My path in education</h3>


{% endblock %}


{% block main %}
<div>
    <h1>tbackend</h1>


    {% for school in schools %}
    
        <img src="{{ school.logo.url }}" maxweight="50px" max height="50px" alt="{{ school.name }} Logo">
        <br>
        <p>{{ school.name }}</p>
        <p>{{ school.location }}</p>
        <p>{{ school.start_date }}</p>
        <p>{{ school.end_date }}</p>

    {% endfor %}
</div>

{% endblock %}

myportfolio/templates/myportfolio/tfrontend.html
{% extends 'myportfolio/base.html' %}

{% load static %}

{% block hero %}


<div>
    <hr>
    <h3 id="active">Education</h3>
</div>

{% endblock %}

{% block title %}

<h3 id="education">My path in education</h3>


{% endblock %}


{% block main %}
<div>
    <h1>tfrontend</h1>


    {% for school in schools %}

    <img src="{{ school.logo.url }}" maxweight="50px" max height="50px" alt="{{ school.name }} Logo">
    <br>
    <p>{{ school.name }}</p>
    <p>{{ school.location }}</p>
    <p>{{ school.start_date }}</p>
    <p>{{ school.end_date }}</p>

    {% endfor %}
</div>

{% endblock %}

myportfolio/templates/myportfolio/tlabs.html
{% extends 'myportfolio/base.html' %}

{% load static %}

{% block hero %}


<div>
    <hr>
    <h3 id="active">Education</h3>
</div>

{% endblock %}

{% block title %}

<h3 id="education">My path in education</h3>


{% endblock %}


{% block main %}
<div>
    <h1>tlabs</h1>


    {% for school in schools %}

    <img src="{{ school.logo.url }}" maxweight="50px" max height="50px" alt="{{ school.name }} Logo">
    <br>
    <p>{{ school.name }}</p>
    <p>{{ school.location }}</p>
    <p>{{ school.start_date }}</p>
    <p>{{ school.end_date }}</p>

    {% endfor %}
</div>

{% endblock %}